### ISSUE TITLE
链接错误：第三章 前端基础能力 基础知识

### ISSUE THREAD

**Issue by wuyiya** [dkypooh/front-end-develop-demo#2]
## 链接错误：第三章 前端基础能力 基础知识

这里H5 多终端适配方案 提供的案例链接有问题：如图

![image](https://user-images.githubusercontent.com/32334581/52041119-6efcb500-2574-11e9-84f7-47730ac12df5.png)

**Comment by dkypooh** [comment]
已添加链接
